# Generated by Django 5.0 on 2024-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
